name: build node application

on:
  push:
    branches:
      - main
    paths:
      - 'index.js'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'index.js'
      - 'package.json'
      - 'package-lock.json'
      
jobs:
    codescan:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Initialize NodeJs
              uses: actions/setup-node@v2
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm ci
              
            - name: CodeQL scan
              uses: github/codeql-action/init@v3
              with:
                languages: JavaScript
            
            - name: codeql build
              uses: github/codeql-action/autobuild@v3
            
            - name: CodeQL analyze
              uses: github/codeql-action/analyze@v3
        
              

            

            