name: mainworkflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run workflow
        uses: ayyoub0400/nodejsactions/.github/workflows/addition.yml
        with:
          number1: 1
          number2: 2
    
            