name: mainworkflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run workflow
        uses: ./.github/workflows/addition.yml
        with:
          number1: 1
          number2: 2
    
            